AWSTemplateFormatVersion: '2010-09-09'
Description: The template used to create an ECS Service from the ECS Console.
Parameters:
  ECSClusterName:
    Type: String
    Default: n11670339-assessment3
  ECSServiceName:
    Type: String
    Default: n11670339-a3-auth-service
  SecurityGroupIDs:
    Type: CommaDelimitedList
    Default: sg-078997505ad1c6bbc,sg-04ba0fa30d603d1ca
  SubnetIDs:
    Type: CommaDelimitedList
    Default: subnet-04ca053dcbe5f49cc,subnet-05a3b8177138c8b14,subnet-075811427d5564cf9
  VpcID:
    Type: String
    Default: vpc-007bab53289655834
  LoadBalancerName:
    Type: String
    Default: n11670339
Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: n11670339-assessment3
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Base: 0
          Weight: 1
      TaskDefinition: arn:aws:ecs:ap-southeast-2:901444280953:task-definition/n11670339-a3-auth:2
      ServiceName: n11670339-a3-auth-service
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: auth
          ContainerPort: 3001
          LoadBalancerName: !Ref AWS::NoValue
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroupIDs
          Subnets: !Ref SubnetIDs
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      Tags:
        - Key: qut-username
          Value: n11670339@qut.edu.au
      PropagateTags: TASK_DEFINITION
      EnableECSManagedTags: true
    DependsOn:
      - ListenerRule
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /health
      Name: ecs-n11670-n11670339-a3-auth-ser
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckProtocol: HTTP
      VpcId: vpc-007bab53289655834
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '300'
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - /auth/*
      ListenerArn: arn:aws:elasticloadbalancing:ap-southeast-2:901444280953:listener/app/n11670339/30fa950843714533/b4133f08c60cb18e
      Priority: '1'
Outputs:
  ClusterName:
    Description: The cluster used to create the service.
    Value: !Ref ECSClusterName
  ECSService:
    Description: The created service.
    Value: !Ref ECSService
  TargetGroup:
    Description: The created target group.
    Value: !Ref TargetGroup
  ListenerRule:
    Description: The created listener rule.
    Value: !Ref ListenerRule