AWSTemplateFormatVersion: '2010-09-09'
Description: The template used to create an ECS Service from the ECS Console.
Parameters:
  ECSClusterName:
    Type: String
    Default: n11670339-assessment3
  ECSServiceName:
    Type: String
    Default: n11670339-a3-web-service
  SecurityGroupIDs:
    Type: CommaDelimitedList
    Default: sg-032bd1ff8cf77dbb9
  SubnetIDs:
    Type: CommaDelimitedList
    Default: subnet-04ca053dcbe5f49cc,subnet-075811427d5564cf9,subnet-05a3b8177138c8b14
  VpcID:
    Type: String
    Default: vpc-007bab53289655834
  LoadBalancerName:
    Type: String
    Default: n11670339
Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: n11670339-assessment3
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Base: 0
          Weight: 1
      TaskDefinition: arn:aws:ecs:ap-southeast-2:901444280953:task-definition/n11670339-a3-web:1
      ServiceName: n11670339-a3-web-service
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: web
          ContainerPort: 3000
          LoadBalancerName: !Ref AWS::NoValue
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroupIDs
          Subnets: !Ref SubnetIDs
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      Tags:
        - Key: qut-username
          Value: n11670339@qut.edu.au
      PropagateTags: TASK_DEFINITION
      EnableECSManagedTags: true
    DependsOn:
      - Listener
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /
      Name: ecs-n11670-n11670339-a3-web-serv
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckProtocol: HTTP
      VpcId: vpc-007bab53289655834
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '300'
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: arn:aws:elasticloadbalancing:ap-southeast-2:901444280953:loadbalancer/app/n11670339/30fa950843714533
      Port: '443'
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:ap-southeast-2:901444280953:certificate/15bee52a-bdf1-42e9-985c-1f0206cb267b
Outputs:
  ClusterName:
    Description: The cluster used to create the service.
    Value: !Ref ECSClusterName
  ECSService:
    Description: The created service.
    Value: !Ref ECSService
  Listener:
    Description: The created listener.
    Value: !Ref Listener
  TargetGroup:
    Description: The created target group.
    Value: !Ref TargetGroup